use std::fs;

use crate::core::skill_files::list_files;

#[test]
fn list_files_excludes_skilldo_cache_metadata() {
    let dir = tempfile::tempdir().expect("tempdir");
    fs::write(dir.path().join("SKILL.md"), "skill").unwrap();
    fs::write(dir.path().join(".skilldo-cache.json"), "generated metadata").unwrap();
    fs::create_dir_all(dir.path().join("__pycache__")).unwrap();
    fs::write(
        dir.path().join("__pycache__/module.pyc"),
        "generated bytecode",
    )
    .unwrap();
    fs::write(dir.path().join("module.pyc"), "generated bytecode").unwrap();

    let files = list_files(dir.path()).unwrap();
    let paths: Vec<_> = files.iter().map(|file| file.path.as_str()).collect();

    assert_eq!(paths, vec!["SKILL.md"]);
}
